"""Add sort_order field to sliders table

Revision ID: 2dbea6e6d8f4
Revises: d3f7ea5b4b8b
Create Date: 2025-10-10 09:17:02.360726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbea6e6d8f4'
down_revision = 'd3f7ea5b4b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sliders', schema=None) as batch_op:
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
